# This file is used for general content and settings.

# This data is used for the metatags and on the homepage.
title: Headless Ninja
description: Magically uniting the best of Drupal and React. We take care of the boring stuff.

# Open source project data
projects:
  drupal:
    hn:
      page: https://www.drupal.org/project/hn
      nid: 2887044
  github:
    hn:
      user: headless-ninja
      repo: javascript